### ISSUE TITLE
Stuck at "Trying to connect to logon.server.com"

### ISSUE THREAD

**Issue by sikkgit** [Artanidos/WotlkBot#1]
Hello! Thanks for making this available! 

I can't seem to figure out this issue with connectivity to the server. **WotlkBot.exe** is getting stuck at "Trying to connect to logon.server.com". **WotlkBotGui.exe** also gets stuck (not getting feedback, though) after pressing Start. I assume it's the same error.

Some logs, if it helps:

- **NETWORK_LOG:**

```
[04:20:40][Network]Sending packet Logon Server Packet: AUTH_LOGON_CHALLENGE. Length: 42 Number: 1
[04:20:40][Network]Handling packet: Logon Server Packet: AUTH_LOGON_CHALLENGE
[04:20:40][Network]Sending packet Logon Server Packet: AUTH_LOGON_PROOF. Length: 75 Number: 2
[04:20:40][Network]Handling packet: Logon Server Packet: AUTH_LOGON_PROOF
```

- **PACKET_LOG:**

```
[04:20:40][Packet]
{Client->Server} Packet: (0x0000) Logon Server Packet: AUTH_LOGON_CHALLENGE PacketSize = 42 Number = 1
|------------------------------------------------|----------------|
|00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F |0123456789ABCDEF|
|------------------------------------------------|----------------|
|00 03 26 00 57 6F 57 00 03 03 05 34 30 36 38 78 |..&.WoW....4068x|
|00 6E 69 57 00 42 47 6E 65 01 00 00 00 7F 00 00 |.niW.BGne......|
|01 08 43 4F 4E 54 53 49 54 45                   |..USER      |
-------------------------------------------------------------------
[04:20:40][Packet]
{Client<-Server} Packet: (0x0000) Logon Server Packet: AUTH_LOGON_CHALLENGE PacketSize = 119
|------------------------------------------------|----------------|
|00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F |0123456789ABCDEF|
|------------------------------------------------|----------------|
|00 00 00 20 65 67 3A 0C 34 B9 54 DB 96 69 70 40 |... eg:.4.T..ip@|
|66 84 3B B6 F1 74 2A 26 6A D4 0E 56 45 38 2A F4 |f.;..t*&j..VE8*.|
|43 90 3A 01 07 20 B7 9B 3E 2A 87 82 3C AB 8F 5E |C.:.. ..>*..<..^|
|BF BF 8E B1 01 08 53 50 06 29 8B 5B AD BD 5B 53 |......SP.).[..[S|
|E1 89 5E 64 4B 89 C7 A4 AF A3 8E F0 21 05 7A 62 |..^dK.......!.zb|
|9D C7 E7 C7 B4 DC 5E E2 26 3D 7E F6 50 0D D7 7E |......^.&=~.P..~|
|4B F9 CC 97 81 63 BA A3 1E 99 A0 0B 21 57 FC 37 |K....c......!W.7|
|3F B3 69 CD D2 F1 00                            |?.i....         |
-------------------------------------------------------------------
[04:20:40][Packet]
{Client->Server} Packet: (0x0001) Logon Server Packet: AUTH_LOGON_PROOF PacketSize = 75 Number = 2
|------------------------------------------------|----------------|
|00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F |0123456789ABCDEF|
|------------------------------------------------|----------------|
|01 B0 61 0E 9C 76 38 EE 32 90 D8 06 AA 2B 89 DF |..a..v8.2....+..|
|35 49 32 2E A4 50 7E 82 C5 72 5C 8C 4E F3 1C 54 |5I2..P~..r\.N..T|
|84 53 7A 9A 02 B1 04 D4 3A F3 91 9C 3C 33 F2 5E |.Sz.....:...<3.^|
|42 41 44 57 0A BC EB CE FF 6F FA 01 EF 65 9F DC |BADW.....o...e..|
|EA C8 59 10 B7 BE 44 D3 B9 00 00                |..Y...D....     |
-------------------------------------------------------------------
[04:20:40][Packet]
{Client<-Server} Packet: (0x0001) Logon Server Packet: AUTH_LOGON_PROOF PacketSize = 2
|------------------------------------------------|----------------|
|00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F |0123456789ABCDEF|
|------------------------------------------------|----------------|
|01 09                                           |..              |
-------------------------------------------------------------------
```

**Comment by Artanidos** [comment]
I would recommend to have a look at the logs on the server first.
Would be best to try with a local AzerothCore installation.

**Comment by sikkgit** [comment]
Thank you for your suggestion!

I tried with a local AzerothCore installation (Docker) and it worked, the character connected to the worldserver and joined the realm.

On a remote installation it connects fine to the remote authserver on port 3724, but it gets stuck trying to connect to the worldserver. Looked through the packets on port 8085 and it looks like it's trying to connect to 127.0.0.1 even though another Host is setup.

**Comment by Artanidos** [comment]
Found it in LogonServerClient.Authenticate
packet.Write((byte)127); packet.Write((byte)0); packet.Write((byte)0); packet.Write((byte)1);

**Comment by sikkgit** [comment]
Thank you for your reply!

After digging deeper with packet inspection, it looks like the server sends back "Authentication Logon Proof" with "Error: Invalid game version (0x09)". This only happens on external servers.

**Local server (127.0.0.1):**

```
    Command: Authentication Logon Proof (0x01)
    Error: Success (0x00)
    SRP M2: ef3a00e24bab121f4a8758744a7e3b3d6a84710f
    Account Flags: 0x00800000
    Hardware Survey ID: 0
    Unknown Flags: 0x0000
```

**External server:**

```
    Command: Authentication Logon Proof (0x01)
    Error: Invalid game version (0x09)
```

Both servers are running AzerothCore on latest revision with similar configuration.

I have looked at CRC hash and other encrypted exchanged data but I can't figure out what the issue is. Do you have an idea on what might cause this?

Thank you!

**Comment by Artanidos** [comment]
Have a look at Config.cs
           Version.major = 3;
            Version.minor = 3;
            Version.update = 5;
            Version.build = 12340;
Maybe your external server uses a different version?
Also these other static bytes that are sent in the Authenticate method look strange to me.
Actually I have no idea, this part of code comes from https://github.com/justMaku/mClient
Maybe you talk to Michał Kałużny.
My personal intent was to be able to play Wow alone offline ;-)
